/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainAboutNationalParkRouteImport } from './routes/(main)/about/national-park'
import { Route as mainAboutHistoryRouteImport } from './routes/(main)/about/history'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutNationalParkRoute = mainAboutNationalParkRouteImport.update({
  id: '/about/national-park',
  path: '/about/national-park',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutHistoryRoute = mainAboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/about/history': typeof mainAboutHistoryRoute
  '/about/national-park': typeof mainAboutNationalParkRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/about/history': typeof mainAboutHistoryRoute
  '/about/national-park': typeof mainAboutNationalParkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/(main)/about/history': typeof mainAboutHistoryRoute
  '/(main)/about/national-park': typeof mainAboutNationalParkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about/history' | '/about/national-park'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about/history' | '/about/national-park'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/'
    | '/(main)/about/history'
    | '/(main)/about/national-park'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about/national-park': {
      id: '/(main)/about/national-park'
      path: '/about/national-park'
      fullPath: '/about/national-park'
      preLoaderRoute: typeof mainAboutNationalParkRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about/history': {
      id: '/(main)/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof mainAboutHistoryRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainAboutHistoryRoute: typeof mainAboutHistoryRoute
  mainAboutNationalParkRoute: typeof mainAboutNationalParkRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainAboutHistoryRoute: mainAboutHistoryRoute,
  mainAboutNationalParkRoute: mainAboutNationalParkRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
